<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\RiskAssessment;

class RiskAssessmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Risk descriptions mapping
        $riskDescriptions = [
            'M01' => 'Data Peti kemas tidak tercatat atau salah',
            'M02' => 'Penempatan peti kemas tidak sesuai',
            'M03' => 'Kerusakan alat bongkar muat',
            'M04' => 'Jadwal kapal tumpang tindih',
            'M05' => 'Kapal pandu tidak tersedia saat dibutuhkan',
            'M06' => 'Terlambatnya jadwal distribusi logistik',
            'M07' => 'Laporan tidak terkirim tepat waktu',
            'M08' => 'Data kapal dan peti kemas tidak sinkron',
            'M09' => 'Kecelakaan kerja saat bongkar muat',
            'M10' => 'Penundaan sandar dan bongkar muat akibat cuaca',
            'M11' => 'Rusaknya jalan pelabuhan atau dermaga',
            'M12' => 'Alat berat digunakan melebihi batas beban',
            'M13' => 'Penumpukan barang tidak rapi',
            'M14' => 'Overload penumpukan di lapangan peti kemas',
            'M15' => 'Terjadi salah komunikasi antara pandu & kapal',
            'M16' => 'Waktu sandar terlalu lama',
            'M17' => 'Barang tidak terpantau',
            'M18' => 'Barang salah kirim',
            'M19' => 'Perintah kerja tidak tersampaikan',
            'M20' => 'Informasi status kapal tidak seragam',
        ];

        // First 100 records from FMEA data
        $assessmentData = [
            // Subiyanto - Manajer Bistek Operasional (Records 1-20)
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M01', 'severity' => 6, 'occurrence' => 8, 'detection' => 6],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M02', 'severity' => 3, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M03', 'severity' => 9, 'occurrence' => 3, 'detection' => 3],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M04', 'severity' => 5, 'occurrence' => 8, 'detection' => 6],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M05', 'severity' => 5, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M06', 'severity' => 7, 'occurrence' => 7, 'detection' => 5],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M07', 'severity' => 5, 'occurrence' => 8, 'detection' => 4],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M08', 'severity' => 7, 'occurrence' => 7, 'detection' => 8],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M09', 'severity' => 10, 'occurrence' => 4, 'detection' => 6],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M10', 'severity' => 9, 'occurrence' => 8, 'detection' => 4],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M11', 'severity' => 6, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M12', 'severity' => 7, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M13', 'severity' => 5, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M14', 'severity' => 6, 'occurrence' => 6, 'detection' => 6],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M16', 'severity' => 5, 'occurrence' => 7, 'detection' => 5],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 4, 'detection' => 5],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M18', 'severity' => 6, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M19', 'severity' => 5, 'occurrence' => 7, 'detection' => 4],
            ['name' => 'Subiyanto', 'job' => 'Manajer Bistek Operasional', 'code' => 'M20', 'severity' => 7, 'occurrence' => 8, 'detection' => 5],

            // Samabudi Giawa - Petugas Lapangan Operasional (Records 21-40)
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 6, 'occurrence' => 7, 'detection' => 4],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 3, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 7, 'occurrence' => 4, 'detection' => 7],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 7, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 9, 'occurrence' => 7, 'detection' => 4],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 8, 'occurrence' => 4, 'detection' => 3],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 7, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 6, 'occurrence' => 6, 'detection' => 8],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 9, 'occurrence' => 4, 'detection' => 5],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 5, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 7, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 4, 'occurrence' => 7, 'detection' => 2],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 7, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 5, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 7, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 5, 'occurrence' => 5, 'detection' => 6],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 4, 'detection' => 5],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 7, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 6, 'occurrence' => 7, 'detection' => 4],
            ['name' => 'Samabudi Giawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 7, 'occurrence' => 7, 'detection' => 3],

            // Rosihin Anwar - Petugas Lapangan Operasional (Records 41-60)
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 7, 'occurrence' => 8, 'detection' => 5],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 5, 'occurrence' => 4, 'detection' => 3],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 8, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 6, 'occurrence' => 5, 'detection' => 6],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 7, 'occurrence' => 8, 'detection' => 5],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 4, 'occurrence' => 9, 'detection' => 5],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 8, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 8, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 9, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 5, 'occurrence' => 6, 'detection' => 6],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 7, 'occurrence' => 4, 'detection' => 2],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 5, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 5, 'occurrence' => 6, 'detection' => 2],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 6, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 5, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 7, 'occurrence' => 4, 'detection' => 2],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 6, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Rosihin Anwar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 6, 'occurrence' => 7, 'detection' => 4],

            // Abner Sitompul - Petugas Lapangan Operasional (Records 61-80)
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 6, 'occurrence' => 7, 'detection' => 2],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 4, 'occurrence' => 4, 'detection' => 2],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 7, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 5, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 7, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 4, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 5, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 7, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 8, 'occurrence' => 4, 'detection' => 2],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 6, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 5, 'occurrence' => 2, 'detection' => 2],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 5, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 3, 'occurrence' => 7, 'detection' => 2],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 4, 'occurrence' => 6, 'detection' => 2],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 6, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 6, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 6, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 5, 'occurrence' => 7, 'detection' => 5],
            ['name' => 'Abner Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 6, 'occurrence' => 7, 'detection' => 4],

            // Hottand Hutagalung - Petugas Lapangan Operasional (Records 81-100)
            ['name' => 'Hottand Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 7, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Hottand Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 3, 'occurrence' => 4, 'detection' => 1],
            ['name' => 'Hottand Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 6, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Hottand Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 6, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Hottand Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 7, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Hottand Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 3, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Hottand Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 8, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Hottand Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 8, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Hottand Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 10, 'occurrence' => 4, 'detection' => 5],
            ['name' => 'Hottand Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 6, 'occurrence' => 7, 'detection' => 2],
            ['name' => 'Hottand Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 4, 'occurrence' => 4, 'detection' => 1],
            ['name' => 'Hotland Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 5, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Hotland Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 4, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Hotland Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 5, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Hotland Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Hotland Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 5, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Hotland Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Hotland Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 6, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Hotland Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 5, 'occurrence' => 7, 'detection' => 3],
            ['name' => 'Hotland Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 6, 'occurrence' => 7, 'detection' => 4],

            // Yanuari Halawa - Petugas Lapangan Operasional (Records 101-120)
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 7, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 3, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 7, 'occurrence' => 4, 'detection' => 7],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 7, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 7, 'occurrence' => 6, 'detection' => 2],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 8, 'occurrence' => 4, 'detection' => 3],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 7, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 7, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 8, 'occurrence' => 3, 'detection' => 6],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 6, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 5, 'occurrence' => 2, 'detection' => 2],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 5, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 5, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 5, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 5, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 7, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 6, 'occurrence' => 8, 'detection' => 3],
            ['name' => 'Yanuari Halawa', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 6, 'occurrence' => 7, 'detection' => 4],

            // Gomgom Wisastro Ujung - Petugas Lapangan Operasional (Records 121-140)
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 7, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 3, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 7, 'occurrence' => 4, 'detection' => 7],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 10, 'occurrence' => 3, 'detection' => 8],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 7, 'occurrence' => 6, 'detection' => 8],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 8, 'occurrence' => 7, 'detection' => 10],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 4, 'occurrence' => 6, 'detection' => 10],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 8, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 10, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 6, 'occurrence' => 7, 'detection' => 2],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 4, 'occurrence' => 4, 'detection' => 1],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 5, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 5, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 5, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 5, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 7, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 7, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 6, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Gomgom Wisastro Ujung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 6, 'occurrence' => 6, 'detection' => 4],

            // Jhonny Tua Sambaton - Petugas Lapangan Operasional (Records 141-160)
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 6, 'occurrence' => 7, 'detection' => 6],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 3, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 9, 'occurrence' => 3, 'detection' => 3],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 5, 'occurrence' => 8, 'detection' => 6],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 5, 'occurrence' => 4, 'detection' => 2],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 4, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 8, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 7, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 10, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 6, 'occurrence' => 7, 'detection' => 2],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 5, 'occurrence' => 2, 'detection' => 2],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 5, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 4, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 4, 'occurrence' => 3, 'detection' => 3],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 6, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 6, 'occurrence' => 3, 'detection' => 3],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 5, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Jhonny Tua Sambaton', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 5, 'occurrence' => 8, 'detection' => 4],

            // Banje Gusra Panggabean - Petugas Lapangan Operasional (Records 161-180)
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 6, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 2, 'occurrence' => 5, 'detection' => 1],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 7, 'occurrence' => 2, 'detection' => 4],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 3, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 5, 'occurrence' => 7, 'detection' => 3],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 4, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 5, 'occurrence' => 7, 'detection' => 3],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 6, 'occurrence' => 7, 'detection' => 4],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 9, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 6, 'occurrence' => 7, 'detection' => 5],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 5, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 4, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 4, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 5, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 5, 'occurrence' => 4, 'detection' => 3],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 5, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 7, 'occurrence' => 2, 'detection' => 4],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 5, 'occurrence' => 7, 'detection' => 4],
            ['name' => 'Banje Gusra Panggabean', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 6, 'occurrence' => 7, 'detection' => 3],

            // Minar Butar-Butar - Petugas Lapangan Operasional (Records 181-200)
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 6, 'occurrence' => 7, 'detection' => 4],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 4, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 7, 'occurrence' => 3, 'detection' => 2],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 9, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 7, 'occurrence' => 7, 'detection' => 4],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 6, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 7, 'occurrence' => 8, 'detection' => 4],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 7, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 9, 'occurrence' => 3, 'detection' => 6],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 7, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 7, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 6, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 3, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 5, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 3, 'detection' => 3],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 5, 'occurrence' => 7, 'detection' => 3],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 7, 'occurrence' => 2, 'detection' => 2],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 6, 'occurrence' => 7, 'detection' => 4],
            ['name' => 'Minar Butar-Butar', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 5, 'occurrence' => 8, 'detection' => 4],

            // Frames Francois Lumbartobing - Petugas Lapangan Operasional (Records 201-220)
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 6, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 2, 'occurrence' => 5, 'detection' => 1],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 7, 'occurrence' => 2, 'detection' => 4],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 3, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 5, 'occurrence' => 7, 'detection' => 3],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 4, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 5, 'occurrence' => 7, 'detection' => 3],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 7, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 9, 'occurrence' => 2, 'detection' => 6],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 7, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 7, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 6, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 4, 'occurrence' => 6, 'detection' => 2],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 5, 'occurrence' => 6, 'detection' => 2],
            ['name' => 'Frames Francois Lumbartobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 5, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Frames Francois Lumbantobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 6, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Frames Francois Lumbantobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 4, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Frames Francois Lumbantobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 7, 'occurrence' => 3, 'detection' => 3],
            ['name' => 'Frames Francois Lumbantobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 5, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Frames Francois Lumbantobing', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 6, 'occurrence' => 8, 'detection' => 3],

            // Santo Riris Martto Hutagalung - Petugas Lapangan Operasional (Records 221-240)
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 6, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 2, 'occurrence' => 5, 'detection' => 1],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 7, 'occurrence' => 2, 'detection' => 4],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 3, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 6, 'occurrence' => 7, 'detection' => 3],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 5, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 7, 'occurrence' => 8, 'detection' => 4],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 7, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 9, 'occurrence' => 3, 'detection' => 7],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 6, 'occurrence' => 7, 'detection' => 2],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 5, 'occurrence' => 2, 'detection' => 2],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 5, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 4, 'occurrence' => 3, 'detection' => 2],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 4, 'occurrence' => 4, 'detection' => 2],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 6, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 7, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 6, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Santo Riris Martto Hutagalung', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 5, 'occurrence' => 6, 'detection' => 3],

            // Irfan Stumreang - Petugas Lapangan Operasional (Records 241-260)
            ['name' => 'Irfan Stumreang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 7, 'occurrence' => 9, 'detection' => 6],
            ['name' => 'Irfan Stumreang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 5, 'occurrence' => 4, 'detection' => 3],
            ['name' => 'Irfan Stumreang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 8, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Irfan Stumreang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 6, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Irfan Stumreang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 6, 'occurrence' => 4, 'detection' => 3],
            ['name' => 'Irfan Stumreang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 3, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 8, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 7, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 10, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 5, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 7, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 4, 'occurrence' => 7, 'detection' => 2],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 3, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 7, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 3, 'detection' => 3],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 5, 'occurrence' => 7, 'detection' => 3],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 6, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 6, 'occurrence' => 7, 'detection' => 5],
            ['name' => 'Irfan Stumeng', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 7, 'occurrence' => 5, 'detection' => 5],

            // Ahmad Mulyadi Strompul - Petugas Lapangan Operasional (Records 261-280)
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 6, 'occurrence' => 8, 'detection' => 6],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 3, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 9, 'occurrence' => 3, 'detection' => 3],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 7, 'occurrence' => 8, 'detection' => 2],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 7, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 8, 'occurrence' => 4, 'detection' => 3],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 7, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 6, 'occurrence' => 6, 'detection' => 8],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 10, 'occurrence' => 2, 'detection' => 6],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 6, 'occurrence' => 7, 'detection' => 2],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 5, 'occurrence' => 2, 'detection' => 2],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 5, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 5, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 5, 'occurrence' => 6, 'detection' => 3],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 5, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Ahmad Mulyadi Strompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 4, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Ahmad Mulyadi Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 6, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Ahmad Mulyadi Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 5, 'occurrence' => 7, 'detection' => 5],
            ['name' => 'Ahmad Mulyadi Sitompul', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 5, 'occurrence' => 7, 'detection' => 4],

            // Ruill Shiite - Petugas Lapangan Operasional (Records 281-300)
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 6, 'occurrence' => 9, 'detection' => 4],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 4, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 7, 'occurrence' => 2, 'detection' => 4],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 3, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 7, 'occurrence' => 7, 'detection' => 4],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 5, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 7, 'occurrence' => 8, 'detection' => 4],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 5, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 10, 'occurrence' => 2, 'detection' => 5],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 6, 'occurrence' => 7, 'detection' => 2],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 5, 'occurrence' => 2, 'detection' => 2],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 5, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 4, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 5, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 5, 'detection' => 4],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 5, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 4, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 7, 'occurrence' => 3, 'detection' => 3],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 4, 'occurrence' => 6, 'detection' => 4],
            ['name' => 'Ruill Shiite', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 5, 'occurrence' => 8, 'detection' => 3],

            // Riston Sitohang - Petugas Lapangan Operasional (Records 301-320)
            ['name' => 'Riston Sitohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M01', 'severity' => 6, 'occurrence' => 9, 'detection' => 4],
            ['name' => 'Riston Sitohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M02', 'severity' => 4, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Riston Sitohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M03', 'severity' => 7, 'occurrence' => 3, 'detection' => 2],
            ['name' => 'Riston Sitohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M04', 'severity' => 7, 'occurrence' => 6, 'detection' => 7],
            ['name' => 'Riston Sitohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M05', 'severity' => 6, 'occurrence' => 8, 'detection' => 5],
            ['name' => 'Riston Sitohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M06', 'severity' => 4, 'occurrence' => 3, 'detection' => 4],
            ['name' => 'Riston Sitohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M07', 'severity' => 5, 'occurrence' => 7, 'detection' => 3],
            ['name' => 'Riston Sitohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M08', 'severity' => 7, 'occurrence' => 6, 'detection' => 5],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M09', 'severity' => 10, 'occurrence' => 2, 'detection' => 5],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M10', 'severity' => 6, 'occurrence' => 7, 'detection' => 2],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M11', 'severity' => 4, 'occurrence' => 4, 'detection' => 1],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M12', 'severity' => 5, 'occurrence' => 5, 'detection' => 2],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M13', 'severity' => 4, 'occurrence' => 4, 'detection' => 4],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M14', 'severity' => 4, 'occurrence' => 3, 'detection' => 3],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M15', 'severity' => 6, 'occurrence' => 3, 'detection' => 3],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M16', 'severity' => 5, 'occurrence' => 7, 'detection' => 3],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M17', 'severity' => 5, 'occurrence' => 5, 'detection' => 5],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M18', 'severity' => 6, 'occurrence' => 3, 'detection' => 5],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M19', 'severity' => 6, 'occurrence' => 5, 'detection' => 3],
            ['name' => 'Riston Sirohang', 'job' => 'Petugas Lapangan Operasional', 'code' => 'M20', 'severity' => 6, 'occurrence' => 7, 'detection' => 3],
        ];

        // Create assessments
        foreach ($assessmentData as $data) {
            RiskAssessment::create([
                'respondent_name' => $data['name'],
                'respondent_job' => $data['job'],
                'risk_code' => $data['code'],
                'risk_description' => $riskDescriptions[$data['code']],
                'severity' => $data['severity'],
                'occurrence' => $data['occurrence'],
                'detection' => $data['detection'],
            ]);
        }
    }
}
